/* ============================================================
   HET ONEERLIJKE SPEL — vragen.js
   Ingebouwde vragenset Kinderboekenweek 2026

   Vraagtype:
   - 'meerkeuze': opties[] + correct (nulgebaseerde index)
   ============================================================ */

const STANDAARD_VRAGEN = [
  {
    id: 'kbw26-01', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wat is het officiële thema van de Kinderboekenweek 2026?',
    opties: ['In de schijnwerpers', 'Spot aan!', 'Het grote boekenpodium', 'Laat je horen!'],
    correct: 1,
    toelichting: 'Het officiële thema van de Kinderboekenweek 2026 is “Spot aan!”.',
  },
  {
    id: 'kbw26-02', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wanneer vindt de Kinderboekenweek 2026 plaats?',
    opties: ['1 tot en met 12 september', '20 september tot en met 1 oktober', '30 september tot en met 11 oktober', '1 tot en met 10 november'],
    correct: 2,
    toelichting: 'De Kinderboekenweek 2026 vindt plaats van 30 september tot en met 11 oktober.',
  },
  {
    id: 'kbw26-03', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wat betekent ‘spot’ in de titel Spot aan!?',
    opties: ['Een plek op de vloer', 'Een grap over iemand', 'Een lamp die iets of iemand uitlicht', 'Een versiering op een boek'],
    correct: 2,
    toelichting: 'Een spot is een lamp waarmee iets of iemand extra wordt uitgelicht.',
  },
  {
    id: 'kbw26-04', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wie zorgt er tijdens een voorstelling meestal voor dat de juiste lampen op het juiste moment aangaan?',
    opties: ['De schrijver', 'De lichttechnicus', 'De kaartverkoper', 'De acteur'],
    correct: 1,
    toelichting: 'De lichttechnicus bedient en programmeert de belichting van een voorstelling.',
  },
  {
    id: 'kbw26-05', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wie schrijft het Kinderboekenweekgeschenk van 2026?',
    opties: ['Milouska Meulens', 'Jacques Vriens', 'Simon van der Geest', 'Harmen van Straaten'],
    correct: 0,
    toelichting: 'Milouska Meulens schrijft het Kinderboekenweekgeschenk “Terug naar de schoenenboom”.',
  },
  {
    id: 'kbw26-06', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Hoe krijg je tijdens de Kinderboekenweek meestal het Kinderboekenweekgeschenk?',
    opties: ['Je leent drie boeken bij de bibliotheek', 'Je koopt voor een bepaald bedrag aan kinderboeken', 'Je schrijft een boekverslag', 'Iedere leerling krijgt het automatisch op school'],
    correct: 1,
    toelichting: 'In 2026 krijg je het geschenk bij aankoop van minimaal € 13,50 aan kinderboeken.',
  },
  {
    id: 'kbw26-07', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Waarvoor wordt de Gouden Griffel uitgereikt?',
    opties: ['Voor het mooist geïllustreerde kinderboek', 'Voor het best geschreven kinderboek', 'Voor het best verkochte kinderboek', 'Voor het grappigste kinderboek'],
    correct: 1,
    toelichting: 'De Gouden Griffel is de prijs voor het best geschreven kinderboek.',
  },
  {
    id: 'kbw26-08', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Waarvoor wordt het Gouden Penseel uitgereikt?',
    opties: ['Voor bijzondere illustraties in een kinderboek', 'Voor een mooi handschrift', 'Voor het beste toneelscript', 'Voor de mooiste boekwinkel'],
    correct: 0,
    toelichting: 'Het Gouden Penseel wordt uitgereikt voor bijzondere illustraties in een kinderboek.',
  },
  {
    id: 'kbw26-09', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wie bepaalt de winnaars van de Nederlandse Kinderjury?',
    opties: ['Alleen schrijvers', 'Alleen leerkrachten', 'Kinderen', 'Boekverkopers'],
    correct: 2,
    toelichting: 'Kinderen van 7 tot en met 12 jaar bepalen mee welke boeken de publieksprijs winnen.',
  },
  {
    id: 'kbw26-10', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wat betekent het wanneer iemand plankenkoorts heeft?',
    opties: ['Diegene is bang voor houten vloeren', 'Diegene is zenuwachtig voor een optreden', 'Diegene vergeet steeds zijn boek', 'Diegene wil niet achter de schermen werken'],
    correct: 1,
    toelichting: 'Plankenkoorts betekent dat iemand zenuwachtig is voor een optreden.',
  },
  {
    id: 'kbw26-11', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Een klas maakt van een boek een toneelstuk. Wat moeten zij meestal als eerste doen?',
    opties: ['Het einde van het verhaal veranderen', 'Bepalen welke scènes belangrijk zijn', 'Kaartjes verkopen', 'Applaus oefenen'],
    correct: 1,
    toelichting: 'Eerst bepaal je welke scènes nodig zijn om het verhaal duidelijk en herkenbaar te vertellen.',
  },
  {
    id: 'kbw26-12', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Wat is een belangrijke taak van een regisseur?',
    opties: ['De boeken verkopen', 'De acteurs begeleiden en bepalen hoe scènes worden gespeeld', 'Alle kostuums zelf naaien', 'De zaal schoonmaken'],
    correct: 1,
    toelichting: 'Een regisseur begeleidt de acteurs en bepaalt hoe scènes worden gespeeld.',
  },
  {
    id: 'kbw26-13', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Welk boek is een officiële thematitel voor groep 7/8 bij de Kinderboekenweek 2026?',
    opties: ['Hart van staal', 'De brief voor de koning', 'Kruistocht in spijkerbroek', 'Achtste-groepers huilen niet'],
    correct: 0,
    toelichting: '“Hart van staal” van Simon van der Geest is een officiële thematitel voor groep 7/8.',
  },
  {
    id: 'kbw26-14', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Waarom kiest de Kinderboekenweek ieder jaar een thema?',
    opties: ['Zodat alleen boeken over dat onderwerp gelezen mogen worden', 'Om boeken en activiteiten op een aantrekkelijke manier met elkaar te verbinden', 'Zodat schrijvers weten waarover ze moeten schrijven', 'Omdat ieder kinderboek hetzelfde onderwerp moet hebben'],
    correct: 1,
    toelichting: 'Het thema verbindt boeken en activiteiten op een aantrekkelijke en herkenbare manier.',
  },
  {
    id: 'kbw26-15', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'De Kinderboekenweek 2026 wordt omschreven als één groot open podium. Wat wordt daarmee vooral bedoeld?',
    opties: ['Alleen professionele acteurs mogen optreden', 'Iedereen kan verhalen beleven, vertellen of op een andere manier tot leven brengen', 'Alle boeken moeten op een podium liggen', 'Iedere klas moet een musical uitvoeren'],
    correct: 1,
    toelichting: 'Iedereen kan verhalen beleven en tot leven brengen, bijvoorbeeld met zang, dans, toneel of vertellen.',
  },
  {
    id: 'kbw26-16', type: 'meerkeuze', categorie: 'Kinderboekenweek 2026',
    vraag: 'Een leerling wil een boek presenteren zonder het verhaal te verklappen. Wat is de beste aanpak?',
    opties: ['Het einde uitgebreid vertellen', 'Alleen de titel voorlezen', 'Iets vertellen over het hoofdpersonage, het probleem en waarom het boek spannend is', 'Alle hoofdstukken samenvatten'],
    correct: 2,
    toelichting: 'Vertel genoeg om nieuwsgierig te maken, maar verklap de oplossing en het einde niet.',
  },
  {
    id: 'boeken-01', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie schreef het boek Sjakie en de chocoladefabriek?',
    opties: ['Paul van Loon', 'Roald Dahl', 'Jacques Vriens', 'Jeff Kinney'],
    correct: 1,
    toelichting: 'Roald Dahl schreef “Sjakie en de chocoladefabriek”.',
  },
  {
    id: 'boeken-02', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Welke schrijver bedacht Harry Potter?',
    opties: ['Astrid Lindgren', 'Annie M.G. Schmidt', 'J.K. Rowling', 'Carry Slee'],
    correct: 2,
    toelichting: 'J.K. Rowling bedacht Harry Potter en de wereld waarin zijn verhalen zich afspelen.',
  },
  {
    id: 'boeken-03', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie is de schrijver van de boeken over Dolfje Weerwolfje?',
    opties: ['Paul van Loon', 'Tosca Menten', 'Jan Terlouw', 'Andy Griffiths'],
    correct: 0,
    toelichting: 'Paul van Loon schrijft de boeken over Dolfje Weerwolfje.',
  },
  {
    id: 'boeken-04', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie schreef De Gorgels?',
    opties: ['Jochem Myjer', 'Pieter Koolwijk', 'Harmen van Straaten', 'Simon van der Geest'],
    correct: 0,
    toelichting: 'Jochem Myjer schreef “De Gorgels”.',
  },
  {
    id: 'boeken-05', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie bedacht de verhalen over Jip en Janneke?',
    opties: ['Thea Beckman', 'Annie M.G. Schmidt', 'Astrid Lindgren', 'Francine Oomen'],
    correct: 1,
    toelichting: 'Annie M.G. Schmidt bedacht en schreef de verhalen over Jip en Janneke.',
  },
  {
    id: 'boeken-06', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie schreef de boeken over Mees Kees?',
    opties: ['Mirjam Oldenhave', 'Carry Slee', 'Manon Sikkel', 'Maren Stoffels'],
    correct: 0,
    toelichting: 'Mirjam Oldenhave schreef de boekenserie over Mees Kees.',
  },
  {
    id: 'boeken-07', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Hoe heet de hoofdpersoon uit de boekenserie Dagboek van een muts?',
    opties: ['Nikki', 'Matilda', 'Pippi', 'Rosa'],
    correct: 0,
    toelichting: 'De hoofdpersoon uit “Dagboek van een muts” heet Nikki.',
  },
  {
    id: 'boeken-08', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie is de hoofdpersoon in Het leven van een loser?',
    opties: ['Bram Botermans', 'Dolfje', 'Mees Kees', 'Lampje'],
    correct: 0,
    toelichting: 'Bram Botermans is de hoofdpersoon in “Het leven van een loser”.',
  },
  {
    id: 'boeken-09', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Welke twee namen horen bij de hoofdpersonen en makers van De waanzinnige boomhut?',
    opties: ['Jip en Janneke', 'Andy en Terry', 'Tom en Jerry', 'Theo en Thea'],
    correct: 1,
    toelichting: 'Andy en Terry zijn de hoofdpersonen én de voornamen van de makers Andy Griffiths en Terry Denton.',
  },
  {
    id: 'boeken-10', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie schreef Kruistocht in spijkerbroek?',
    opties: ['Tonke Dragt', 'Jan Terlouw', 'Thea Beckman', 'Jacques Vriens'],
    correct: 2,
    toelichting: 'Thea Beckman schreef “Kruistocht in spijkerbroek”.',
  },
  {
    id: 'boeken-11', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie is de schrijver van De brief voor de koning?',
    opties: ['Tonke Dragt', 'Paul Biegel', 'Jan Terlouw', 'Edward van de Vendel'],
    correct: 0,
    toelichting: 'Tonke Dragt schreef “De brief voor de koning”.',
  },
  {
    id: 'boeken-12', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie bedacht het personage Pippi Langkous?',
    opties: ['Astrid Lindgren', 'Selma Lagerlöf', 'J.K. Rowling', 'Annie M.G. Schmidt'],
    correct: 0,
    toelichting: 'De Zweedse schrijver Astrid Lindgren bedacht Pippi Langkous.',
  },
  {
    id: 'boeken-13', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'In welk boek ontdekt een meisje dat ze voorwerpen kan laten bewegen zonder ze aan te raken?',
    opties: ['Matilda', 'Minoes', 'Lampje', 'Achtste-groepers huilen niet'],
    correct: 0,
    toelichting: 'In “Matilda” ontdekt het gelijknamige meisje dat ze voorwerpen met haar gedachten kan bewegen.',
  },
  {
    id: 'boeken-14', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wat is bijzonder aan Minoes uit het gelijknamige boek?',
    opties: ['Ze kan vliegen', 'Ze was vroeger een kat', 'Ze woont in een chocoladefabriek', 'Ze is een heks'],
    correct: 1,
    toelichting: 'Minoes was vroeger een kat en verandert in een jonge vrouw.',
  },
  {
    id: 'boeken-15', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Hoe heten de tweelingbroers uit de boekenserie De Kameleon?',
    opties: ['Hielke en Sietse', 'Jip en Janneke', 'Andy en Terry', 'Tom en Bram'],
    correct: 0,
    toelichting: 'De tweelingbroers uit “De Kameleon” heten Hielke en Sietse Klinkhamer.',
  },
  {
    id: 'boeken-16', type: 'meerkeuze', categorie: 'Bekende kinderboeken en schrijvers',
    vraag: 'Wie schreef Achtste-groepers huilen niet?',
    opties: ['Jacques Vriens', 'Carry Slee', 'Francine Oomen', 'Jan Terlouw'],
    correct: 0,
    toelichting: 'Jacques Vriens schreef “Achtste-groepers huilen niet”.',
  },
  {
    id: 'verhaal-01', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Voor een voorstelling zijn 240 kaartjes beschikbaar. In de voorverkoop zijn al 178 kaartjes verkocht. Hoeveel kaartjes zijn er nog over?',
    antwoord: '62 kaartjes',
    toelichting: '240 − 178 = 62 kaartjes.',
  },
  {
    id: 'verhaal-02', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'In de theaterzaal staan 18 rijen met in iedere rij 24 stoelen. Hoeveel mensen kunnen er maximaal in de zaal zitten?',
    antwoord: '432 mensen',
    toelichting: '18 × 24 = 432 mensen.',
  },
  {
    id: 'verhaal-03', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Een school verkoopt 275 kaartjes voor een voorstelling. Eén kaartje kost € 6,00. Hoeveel geld levert de kaartverkoop in totaal op?',
    antwoord: '€ 1.650',
    toelichting: '275 × € 6 = € 1.650.',
  },
  {
    id: 'verhaal-04', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'De voorstelling begint om 19.15 uur. Deel 1 duurt 48 minuten, de pauze 20 minuten en deel 2 duurt 57 minuten. Hoe laat is de voorstelling afgelopen?',
    antwoord: '21.20 uur',
    toelichting: '48 + 20 + 57 = 125 minuten, oftewel 2 uur en 5 minuten. 19.15 uur + 2.05 uur = 21.20 uur.',
  },
  {
    id: 'verhaal-05', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Voor een toneelstuk zijn 36 kostuumstukken gemaakt. Daarvan is ⅓ deel voor de hoofdrolspelers. Hoeveel kostuumstukken zijn voor de overige spelers?',
    antwoord: '24 kostuumstukken',
    toelichting: '⅓ van 36 is 12. Er blijven 36 − 12 = 24 kostuumstukken over.',
  },
  {
    id: 'verhaal-06', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Tijdens de Kinderboekenweek kost een boekenpakket normaal € 80. De school krijgt 15% korting. Hoeveel euro moet de school na de korting betalen?',
    antwoord: '€ 68',
    toelichting: '15% van € 80 is € 12. De school betaalt € 80 − € 12 = € 68.',
  },
  {
    id: 'verhaal-07', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Een decorwand is in werkelijkheid 6 meter breed. Op de ontwerptekening wordt de schaal 1 : 50 gebruikt. Hoe breed is de decorwand op de tekening?',
    antwoord: '12 centimeter',
    toelichting: '6 meter is 600 centimeter. 600 ÷ 50 = 12 centimeter.',
  },
  {
    id: 'verhaal-08', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Op het podium hangen 20 spotlights. De lichttechnicus gebruikt 35% voor de voorkant en 25% voor de achterkant. De overige spotlights worden aan de zijkanten gebruikt. Hoeveel spotlights worden aan de zijkanten gebruikt?',
    antwoord: '8 spotlights',
    toelichting: '35% + 25% = 60%, dus 40% blijft over. 40% van 20 is 8 spotlights.',
  },
  {
    id: 'verhaal-09', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Een rechthoekig podium is 9 meter breed en 6 meter diep. Langs de hele rand moet een lichtslang komen. Hoeveel meter lichtslang is minimaal nodig?',
    antwoord: '30 meter',
    toelichting: 'De omtrek is 9 + 6 + 9 + 6 = 30 meter.',
  },
  {
    id: 'verhaal-10', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Vier teams verzamelen boeken voor een boekenpodium. Team 1 verzamelt 18 boeken, team 2 verzamelt 25 boeken, team 3 verzamelt 21 boeken en team 4 verzamelt 16 boeken. De boeken worden eerlijk verdeeld over 5 presentatietafels. Hoeveel boeken komen er op iedere tafel?',
    antwoord: '16 boeken',
    toelichting: '18 + 25 + 21 + 16 = 80 boeken. 80 ÷ 5 = 16 boeken per tafel.',
  },
  {
    id: 'verhaal-11', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'De school heeft 168 boeken gekocht voor de Kinderboekenweek. De boeken worden eerlijk verdeeld over 7 klassen. Hoeveel boeken krijgt iedere klas?',
    antwoord: '24 boeken',
    toelichting: '168 ÷ 7 = 24 boeken per klas.',
  },
  {
    id: 'verhaal-12', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Een klas oefent iedere schooldag 35 minuten voor een voorstelling. Ze oefenen 4 weken lang, steeds 5 dagen per week. Hoeveel uur en minuten oefenen ze in totaal?',
    antwoord: '11 uur en 40 minuten',
    toelichting: '4 × 5 × 35 = 700 minuten. Dat is 11 uur en 40 minuten.',
  },
  {
    id: 'verhaal-13', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Voor één theatergordijn is 7,5 meter stof nodig. De school maakt twee gordijnen. De stof kost € 8 per meter. Hoeveel kost de stof in totaal?',
    antwoord: '€ 120',
    toelichting: '2 × 7,5 = 15 meter stof. 15 × € 8 = € 120.',
  },
  {
    id: 'verhaal-14', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Op woensdag bezoeken 320 mensen de boekenvoorstelling. Op donderdag zijn dat er 25% meer. Hoeveel bezoekers komen er op donderdag?',
    antwoord: '400 bezoekers',
    toelichting: '25% van 320 is 80. Op donderdag komen 320 + 80 = 400 bezoekers.',
  },
  {
    id: 'verhaal-15', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'Een vierkant podium heeft zijden van 8 meter. Iedere vloertegel bedekt precies 1 m². Hoeveel vloertegels zijn nodig om het hele podium te bedekken?',
    antwoord: '64 vloertegels',
    toelichting: 'De oppervlakte is 8 × 8 = 64 m². Er zijn dus 64 vloertegels nodig.',
  },
  {
    id: 'verhaal-16', type: 'open', categorie: 'Verhaalsommen',
    vraag: 'De drukker verpakt programmaboekjes in dozen van 40 stuks. De school heeft 350 programmaboekjes nodig. Hoeveel dozen moet de school minimaal bestellen?',
    antwoord: '9 dozen',
    toelichting: '350 ÷ 40 = 8,75. Omdat je geen deel van een doos kunt bestellen, zijn minimaal 9 dozen nodig.',
  },
  {
    id: 'ww-01', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Yzra heeft drie verschillende boeken __________. (lenen, vd)',
    antwoord: 'geleend',
    toelichting: 'Het voltooid deelwoord van lenen is geleend.',
  },
  {
    id: 'ww-02', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Mikel __________ gisteren niet naar de bibliotheek van zijn moeder. (mogen, vt)',
    antwoord: 'mocht',
    toelichting: 'De verleden tijd van mogen is mocht.',
  },
  {
    id: 'ww-03', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De presentator __________ het volgende optreden aan. (aankondigen, tt)',
    antwoord: 'kondigt',
    toelichting: 'Bij de presentator gebruik je in de tegenwoordige tijd kondigt; “aan” staat al achteraan.',
  },
  {
    id: 'ww-04', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Noor heeft haar favoriete boek aan de klas __________. (presenteren, vd)',
    antwoord: 'gepresenteerd',
    toelichting: 'Het voltooid deelwoord van presenteren is gepresenteerd.',
  },
  {
    id: 'ww-05', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De lichttechnicus __________ voor de voorstelling alle lampen. (controleren, vt)',
    antwoord: 'controleerde',
    toelichting: 'De verleden tijd van controleren is controleerde.',
  },
  {
    id: 'ww-06', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Het publiek __________ aandachtig naar het spannende verhaal. (luisteren, tt)',
    antwoord: 'luistert',
    toelichting: 'Het publiek is enkelvoud, dus in de tegenwoordige tijd wordt het luistert.',
  },
  {
    id: 'ww-07', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De schrijver heeft een verrassend einde __________. (bedenken, vd)',
    antwoord: 'bedacht',
    toelichting: 'Het voltooid deelwoord van bedenken is bedacht.',
  },
  {
    id: 'ww-08', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Tijdens de repetitie __________ Amir zijn tekst helemaal. (vergeten, vt)',
    antwoord: 'vergat',
    toelichting: 'De verleden tijd van vergeten is vergat.',
  },
  {
    id: 'ww-09', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De regisseur __________ welke spelers als eerste het podium op gaan. (bepalen, tt)',
    antwoord: 'bepaalt',
    toelichting: 'Bij de regisseur gebruik je in de tegenwoordige tijd bepaalt.',
  },
  {
    id: 'ww-10', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De kinderen hebben het decor met boeken en gordijnen __________. (versieren, vd)',
    antwoord: 'versierd',
    toelichting: 'Het voltooid deelwoord van versieren is versierd.',
  },
  {
    id: 'ww-11', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De spotlights __________ het hele podium. (verlichten, tt)',
    antwoord: 'verlichten',
    toelichting: 'De spotlights is meervoud, dus de tegenwoordige tijd is verlichten.',
  },
  {
    id: 'ww-12', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Vorige week __________ onze klas een scène uit een boek. (spelen, vt)',
    antwoord: 'speelde',
    toelichting: 'Onze klas is enkelvoud; de verleden tijd van spelen is speelde.',
  },
  {
    id: 'ww-13', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Het nieuwe kinderboek __________ vandaag in de schijnwerpers gezet. (worden, tt)',
    antwoord: 'wordt',
    toelichting: 'Bij het nieuwe kinderboek gebruik je in de tegenwoordige tijd wordt.',
  },
  {
    id: 'ww-14', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Het publiek heeft na afloop luid __________. (applaudisseren, vd)',
    antwoord: 'geapplaudisseerd',
    toelichting: 'Het voltooid deelwoord van applaudisseren is geapplaudisseerd.',
  },
  {
    id: 'ww-15', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. De decorbouwers __________ een grote boekenkast van karton. (maken, vt)',
    antwoord: 'maakten',
    toelichting: 'De decorbouwers is meervoud; de verleden tijd van maken is maakten.',
  },
  {
    id: 'ww-16', type: 'open', categorie: 'Werkwoordspelling',
    vraag: 'Vul de juiste vorm van het werkwoord in. Mila __________ iedere avond een hoofdstuk uit haar boek. (lezen, tt)',
    antwoord: 'leest',
    toelichting: 'Bij Mila gebruik je in de tegenwoordige tijd leest.',
  },
];
